### ISSUE TITLE
Quad doubles

### ISSUE THREAD

**Issue by jjrv** [munrocket/double.js#1]
Inspired by this, I'm probably going to write a quad double library. It will have 5 operations:

- Initialize from a number (trivial) or a sum or product of two numbers.
- Multiply by another quad or number.
- Add / sub another quad or number.
- Compare quads.
- Convert to string by calling `bigfloat` (for debugging only, no need for speed).

There won't be anything else, because the only application I need is polygon clipping. Division is handled by using rational numbers.

[This paper seems promising](https://www.jstage.jst.go.jp/article/nolta/5/1/5_15/_article).

Numbers are represented as objects:

```TypeScript
interface Doubles {
    floats: Float64Array;
    words: Uint32Array;
}
```

The two fields are aliased like this:

```TypeScript
words = new Uint32Array(floats.buffer);
```

The paper calls for functions like `ufp` and `epart` that are best handled by poking IEEE 754 bits directly through integer typed arrays. Function definitions will be like:

```TypeScript
function sum44(a, b, result) { ... }
```

Writing the result to an existing structure avoids memory allocations which involve the 2 aliased typed arrays wrapped in an object.

What do you think? Maybe `double.js` functions could also take a result array to avoid allocating temporaries in longer calculations.

**Comment by munrocket** [comment]
Hello! Yep, i thinked about Quad-double too. But at first I wanted to test the Double-length that's why i created this repository. Also i use this Double.js in my [mandelbrot](https://github.com/munrocket/mandelbrot-set) render and it's works with 3000 multiplication and addition. So it's stable. But also for now I have a trouble now with mult21/div21 and parseDouble/toString for example. You can check travis output with unit-test [here](https://travis-ci.org/munrocket/double.js/jobs/426815877). Note that all trivial error-free operation like quickTwoSum and dekkerMultiplication I inlined into code. In javascript case it's good solution and not so messy. In one-two day I will create handy base class like in decimal.js and your bigFloat library so you migrate faster. If you need typescript we can create .d.ts.

**Comment by munrocket** [comment]
@jjrv thanks for your mention of memory allocation.

Imho main problem of the proposed paper that they heavily use bitwise arithmetic (Algorithm3 and Remark2). It's good in C++ but in javascript it can be hard to implement. When we shift a number, it's converted from a floating point 64 bit number to a 32 bit integer before the bitwise operation, and converted back to a floating point number after the operation ([example](https://stackoverflow.com/questions/41347246/bitwise-or-on-large-values)). That's why we will have bugs for big number stored in 3 components. Do you know how to avoid this? Maybe [QD](http://web.mit.edu/tabbott/Public/quaddouble-debian/qd-2.3.4-old/docs/qd.pdf) is easier in our case?

**Comment by jjrv** [comment]
@munrocket Those can be handled by aliased typed arrays like this (2 versions for handling endianness):

```TypeScript
const floatBuffer = new Float64Array([ -Infinity ]);
const floatWords = new Uint32Array(floatBuffer.buffer);
let ufpMask = floatWords[0];
let ufp;
let log2;

if(ufpMask) {
	ufp = function(x) {
		floatBuffer[0] = x;
		floatWords[0] &= ufpMask;
		floatWords[1] = 0;

		return(floatBuffer[0]);
	}

	log2 = function(x) {
		floatBuffer[0] = x;
		return(((floatWords[0] << 1) >>> 21) - 1023);
	}
} else {
	ufpMask = floatWords[1];

	ufp = function(x) {
		floatBuffer[0] = x;
		floatWords[0] = 0;
		floatWords[1] &= ufpMask;

		return(floatBuffer[0]);
	}

	log2 = function(x) {
		floatBuffer[0] = x;
		return(((floatWords[1] << 1) >>> 21) - 1023);
	}
}
```

**Comment by munrocket** [comment]
@jjrv Cool link. We know now when we will wrong result due to not correct rounding. I wan't to check double.js in 32 bit linux/mac (32bit android/iphone).

Main problem that truncating 53 bit mantissa to 32 bit it's very costly. We can implement Triple with full float and it would be faster and more precisely than Quadriple :D

53*3=159 bit significand for Triple with full float.
32*4 = 128 bit significand for Quadriple with truncated float mantissa.

**Comment by jjrv** [comment]
Quad doubles use 53 bits of mantissa per component. The method by Yamanaka and Oichi loses some bits to overlap leaving 203, but might save time by relaxing the normalization a bit.

There's no need to bit shift floats here.

**Comment by munrocket** [comment]
Oh, I catched this, did not know that we can extract exp value by [buffer binding](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays).

**Comment by munrocket** [comment]
Yep, this paper seems promising.

**Comment by jjrv** [comment]
The rounding issue is extremely subtle. If we look at your `fromSum11` which seems to come from Knuth's `two-sum`:

```JavaScript
  static fromSum11(a, b) {
    let z = a + b;
    let w = z - a;
    let z2 = z - w - a;
    return new Double([z, b - w - z2]);
  }
```

`z` can be wrong by one ULP due to double rounding at least in pre-2016 versions of Chrome on Linux, but this will also affect `w`. Then the second component, effectively the error term, will cancel out the error in `z`. The end result is different but represents the same number.

What I can't figure out yet is if a rounding error could occur while forming the error term, leaving an incorrect overall result. Just analyzing the sum of two doubles is difficult enough, never mind the more complicated operations involving double double inputs or multiplication.

Probably easiest would be to write test cases in C for all the operations, to allow controlling rounding modes on a single machine.

For reference, this is what I get when summing `9007199254740994` and `1 / 65536` (little endian hex dump of the double double IEEE 754 components):

IEEE 754 compliant:
```
4340000000000002 bff0001000000000
```

Double rounded:
```
4340000000000001 3fefffe000000000
```

I used an arbitrary precision math library to sum the components, and in both cases the result was:

```
9007199254740994.9999847412109375
```

So the end result was still correct, although different, due to the double rounding.

No idea if that will always work, but it did for these inputs.

**Comment by jjrv** [comment]
I guess you meant Priest's sum and roundoff error algorithm in the floating point arithmetic handbook. It says "works if ◦ is any of the four rounding modes of IEEE 754-1985". However, "round to nearest applied twice, to 80 and then 64 bits" is not any of those rounding modes. I can't tell if the more complicated algorithm helps or hurts here.

**Comment by munrocket** [comment]
It's the same technique basically and if we will have error in double-length it will appear in quad-length. I am readed Ecmascript 1 and generally speaking engines must have correct rounding. But how it is actually work? We can only fix float without round-to-nearest mode. If it totally broken nothing helps here))

**Comment by munrocket** [comment]
We must port [floating point paranoia](http://www.netlib.org/paranoia/paranoia.c) to javascript :D
Maybe we can do it easily with asm.js.

**Comment by jjrv** [comment]
In any case the double rounding problem only affected x86-based Linux / Mac desktops until 2016, when browsers fixed it. Users have probably updated by now. Luckily IE never had this problem, since it wouldn't get fixed either! Mobile browsers seem to have used 64-bit precision all the time.

I think the best option is to trust the IEEE 754 implementation, and have a fallback that uses one of the many arbitrary precision libraries internally only manipulating integers.

If the double rounding causes problems, test for it and switch to the fallback. Same goes for any additional portability issues that come up.

**Comment by munrocket** [comment]
I am transpiled paranoia.c to js but it's interactive console program and not fit for our purpose. Tests in [this](https://hal.archives-ouvertes.fr/hal-00128124/file/floating-point-article.pdf) paper looks better.

**Comment by munrocket** [comment]
Main problem with this quick algoritms that they not perfectly accurate in js. I thinked that I had an error with parsing String to Double. But after that i used Big.js to split number string accurately into two number. And figured out that after splitting and performing any operation (double * double, double / double and so on) I still have an error in 1e-16. I tested this results with Big.js and WolframAlpha. Now I'm confused little bit. You can check tests in experimental branch.

**Comment by munrocket** [comment]
```
> let string = '3.141592653589793238462643383279502884197169399375105820974';
> let x = parseFloat(string);
> let y = parseFloat(new Big(string).minus(new Big(x)).toString());
> console.log(x + y);
3.1415926535897936
> console.log(new Big(x).add(new Big(y)).toString());
3.1415926535897932384626433832795
```

Error = 2e-16.  But x and y is splitted.

**Comment by munrocket** [comment]
```
> let string = '3.141592653589793238462643383279502884197169399375105820974';
> let bigPi = new Big(string);
> let x = parseFloat(string);
> let y = parseFloat(new Big(string).minus(new Big(x)).toString());
> let doublePi = new Double([x, y]);
> console.log(toString(doublePi));
3.1415926535897932384626433832795

> console.log(toString(doublePi.add(doublePi)));
6.2831853071795865887468670664338

> console.log(bigPi.add(bigPi).round(31).toString());
6.283185307179586476925286766559

> console.log(toString(doublePi.mul(doublePi)));
9.86960440108935957900941120203207

> console.log(bigPi.mul(bigPi).round(31).toString());
9.8696044010893586188344909998762
```

**Comment by jjrv** [comment]
While debugging basic arithmetics, you should use base 16 (or another power of 2) for inputs and outputs. Or just look at a raw hex dump of the component parts. Otherwise you can't really know if the error is in base conversion or arithmetics.
