### ISSUE TITLE
How to use with typescript?

### ISSUE THREAD

**Issue by Riim** [munrocket/double.js#17]
Hi.

My code:
```js
import Double from 'double.js';

export function roundTo(num: number, roundTo: number) {
	roundTo = new Double(1).div(roundTo).toNumber();
	return new Double(Math.floor(num * roundTo)).div(roundTo).toNumber();
}
```
Compiles successfully but on execute:
```
roundTo = new double_js_1.default(1).div(roundTo).toNumber();
              ^
TypeError: double_js_1.default is not a constructor
```

In `double.d.ts`:
```js
export default class Double
```
In `double.js`:
```js
module.exports = factory()
```
`factory` returns class `Double`.
Where default? As far as I understand it should return `{default: Double}`.

**Comment by munrocket** [comment]
I am not tried to use it in typescript project. Maybe “module:false” in package.json?

**Comment by Riim** [comment]
> Maybe “module:false” in package.json?

this won't help.
Try to see this [repository](https://github.com/Riim/omyumyum). It may be a matter of setting `rollup` up correctly or how I [export](https://github.com/Riim/omyumyum/blob/705da72ffbfda82be96597a1358eb85e06b17090/src/OmYumYum.ts#L51).

**Comment by munrocket** [comment]
So, maybe PR?

**Comment by Riim** [comment]
Changed `mandel.wasm` need to add in commit?

**Comment by munrocket** [comment]
Not it is very experimental and with AssemblyScript.

**Comment by Riim** [comment]
Now it works, but there was such a problem:
```js
import BigNumber from 'bignumber.js';
import Double from 'double.js';

export function roundTo(num: number, roundTo: number) {
	roundTo = new Double(1).div(roundTo).toNumber();
	return new Double(Math.floor(num * roundTo)).div(roundTo).toNumber();
}

console.log(roundTo(0.7092179183617962, 0.00001), 0.70921, 'roundTo 1');

export function roundTo2(
	num: BigNumber | number | string,
	roundTo: BigNumber | number | string
): BigNumber {
	roundTo = new BigNumber(1).div(roundTo);

	return new BigNumber(Math.floor(new BigNumber(num).multipliedBy(roundTo).toNumber())).div(
		roundTo
	);
}

console.log(roundTo2(0.7092179183617962, 0.00001).toNumber(), 0.70921, 'roundTo 2');
```
Result:
```
0.7092100000000001 0.70921 roundTo 1
0.70921 0.70921 roundTo 2
```

**Comment by munrocket** [comment]
Probably you should use `round to nearest even` mode in BigNumber to get same results. When you use precise arithmetic you need to be very careful.

**Comment by Riim** [comment]
On the contrary, the result BigNumber.js seems correct to me. It is possible to get the same with Double.js ?

**Comment by munrocket** [comment]
Don't know what are you trying to solve, but you shouldn't use for money calculations.
Numbers like 0.00001 not intuitive for humans, because they truncated.
```
function roundTo(num, r) {
  r = Math.pow(10, 5);
  return new Double(Math.floor(num * r)).div(r).toNumber();
}
roundTo(0.7092179183617962, 5)
//gives 0.70921
```
Or it's a bug with .toNumber(), I need to think here.
```
Double.fromSum11(0.00001, 1).inv().toNumber();
//gives 99999.99999999999
```

**Comment by munrocket** [comment]
Here solution. 0.00001 should be used as string. Because in javascript it's stored as truncated number.
```
let Double = require("double.js")
function roundTo(num, r) {
  r = new Double(r.toString()).inv().toNumber();
  return new Double(Math.floor(num * r)).div(r).toNumber();
}
roundTo(0.7092179183617962, 0.00001)
```

**Comment by Riim** [comment]
Thanks!
