### ISSUE TITLE
Fairer benchmarks

### ISSUE THREAD

**Issue by jjrv** [munrocket/double.js#2]
The benchmark seems to show a massive speed difference between `decimal.js` and `big.js`.

The bignum libraries generally have a precision limit for division operations, for example 20 digits. However Mandelbrot calculations only involve addition / subtraction / multiplication which result in a finite number of bits, so there's no need to round.

The problem for benchmarking is that without rounding, every iteration potentially doubles the number of bits, making the Mandelbrot iteration run in polynomial instead of linear time.

The [bigfloat benchmark code](https://github.com/charto/bigfloat/blob/gh-pages/mandelbrot.js) rounds intermediate results at every iteration.

It seems [decimal.js rounds multiplication results by default](https://github.com/MikeMcl/decimal.js/blob/v10.0.1/decimal.js#L1915) while [big.js does not](https://github.com/MikeMcl/big.js/blob/v5.1.2/big.js#L857), which would explain the apparent speed difference.

**Comment by munrocket** [comment]
Yea, you right, Big.js is faster than bigNumber with rounding. Have we some technique for increasing bigNumber speed also?

**Comment by munrocket** [comment]
Method .round() refactored to .dp() in bigNumber. This libraries become much faster :D

**Comment by munrocket** [comment]
@jjrv fixed. And I am change .sqr() to .mul() from double.js to be fair as much as posible.
