### ISSUE TITLE
Do you have a parser or eval?

### ISSUE THREAD

**Issue by Light-Wizzard** [munrocket/double.js#3]
I am looking for a library that can parse or eval equations, I am using this in Qt Qml Felgo, using Qml JavaScript, do you know if this works in Qml JavaScript Engine also?

**Comment by munrocket** [comment]
This will work if you can use the additional library there or you can copy the es5 / es6 code into the interpreter. It’s plain js.

**Comment by munrocket** [comment]
@Light-Wizzard ok, you can combine somehow math.js with double.js/bigfloat for your Galaxy Calculator.

**Comment by Light-Wizzard** [comment]
Thanks I will look into that now.
